from __future__ import annotations

import os
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parents[2]
PROJECT_ROOT = Path(os.getenv("CODE_AGENT_WORKSPACE", Path.cwd())).resolve()
DEFAULT_TOOL_WORKSPACE = PROJECT_ROOT
MEMORY_ROOT = PROJECT_ROOT / ".code_agent" / "memory"
AGENT_DATA_ROOT = PROJECT_ROOT / ".code_agent"
SESSION_DB_PATH = AGENT_DATA_ROOT / "sessions.sqlite3"
DASHSCOPE_COMPATIBLE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DASHSCOPE_CONTEXT_CACHE_TYPE = "ephemeral"
DEFAULT_MAIN_MODEL = "glm-5.1"
DEFAULT_SUB_AGENT_MODEL = "qwen3.5-plus-2026-04-20"

CONTEXT_WINDOW_TOKENS = 120_000
OUTPUT_TOKEN_RESERVE = 20_000
CONTEXT_EFFECTIVE_LIMIT = CONTEXT_WINDOW_TOKENS - OUTPUT_TOKEN_RESERVE
CONTEXT_BLOCKING_MARGIN = 3_000
CONTEXT_WARNING_MARGIN = 20_000
AUTO_COMPACT_THRESHOLD_RATIO = 0.93
COLLAPSE_COMMIT_RATIO = 0.90
COLLAPSE_BLOCK_SPAWN_RATIO = 0.95
MICRO_COMPACT_IDLE_SECONDS = 300
MICRO_COMPACT_KEEP_RECENT = 2
